/* eslint-disable @typescript-eslint/consistent-type-assertions */
// clerkMiddleware passes a Request that we widen to NextRequest because
// the Clerk types are not aware of Next's extensions.
import { clerkMiddleware, createRouteMatcher } from '@clerk/nextjs/server'
import { NextResponse, type NextRequest } from 'next/server'
import {
  isProtectedPath,
  PROTECTED_PATH_PREFIXES,
} from '@/lib/routing/protected-routes'

// Phase 3 (Supabase-auth elimination, 2026-05-13): the legacy
// Supabase session-refresh middleware path has been removed. Clerk is
// the sole identity provider, so anonymous users no longer need a
// per-host cookie read, a Supabase server-client per request, or a
// refresh-token recovery branch. What remains:
//
//   - security headers (the CSP is generated by clerkMiddleware — see
//     CSP_OPTIONS below)
//   - Clerk session resolution (with a timeout fallback)
//   - protected-path → /login redirect for anonymous traffic
//   - /login + /signup → dashboard redirect for already-signed-in users
//
// The `/login` page itself still exists; Phase 4 of the migration
// deletes it (and the cookie-options / storage-keys helpers that fed
// the old refresh-recovery path).

const SECURITY_HEADERS = {
  'X-Frame-Options': 'DENY',
  'X-Content-Type-Options': 'nosniff',
  'X-XSS-Protection': '1; mode=block',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy':
    'camera=(), microphone=(), geolocation=(), interest-cohort=()',
  'Cross-Origin-Opener-Policy': 'same-origin',
  'Cross-Origin-Resource-Policy': 'same-origin',
}

const PUBLIC_BYPASS_PATHS = [
  '/api/performance/metrics',
  '/api/health',
  // Clerk webhook (verified by Svix signature, must not be gated by auth).
  '/api/webhooks/clerk',
]

// M1 (2026-05-13 audit) / CSP rework (2026-05-16): the Content-Security-
// Policy is generated by clerkMiddleware's `contentSecurityPolicy` option
// instead of being hand-rolled here.
//
// Why: the previous hand-rolled `script-src` used `'strict-dynamic'`, which
// disables host allowlisting. Clerk's own CDN scripts (clerk.browser.js,
// ui.browser.js) are not nonce-tagged, so the browser rejected them and the
// auth UI loaded only by luck (verified on prod, 2026-05-16). Letting Clerk
// own the CSP fixes that: with `strict: true` Clerk mints a per-request
// nonce, adds `'strict-dynamic'` + that nonce to `script-src`, and — the
// key part — propagates the nonce to the request headers so Next.js and
// Clerk's own <ClerkProvider> tag their scripts with it. Under
// `strict-dynamic` the browser then transitively trusts whatever those
// nonced scripts load (Turnstile, Maps, AdSense), so no script-src host
// allowlist is needed.
//
// `directives` are merged (union) with Clerk's built-in defaults; here we
// add the app's own non-Clerk needs (Supabase, Google Fonts/Maps/AdSense,
// the frame-ancestors lock). Production only — matching the prior policy;
// `next dev` keeps an unrestricted CSP so React Refresh etc. still work.
const CSP_OPTIONS =
  process.env.NODE_ENV === 'production'
    ? {
        strict: true,
        directives: {
          'default-src': ["'self'"],
          // 'strict-dynamic' + the nonce are added by Clerk's strict mode;
          // 'wasm-unsafe-eval' is for Cloudflare Turnstile's WASM module.
          'script-src': ["'wasm-unsafe-eval'"],
          'style-src': ["'unsafe-inline'", 'https://fonts.googleapis.com'],
          'font-src': ["'self'", 'https://fonts.gstatic.com'],
          'img-src': ["'self'", 'data:', 'https:', 'blob:'],
          'connect-src': [
            'https://*.supabase.co',
            'wss://*.supabase.co',
            'https://*.clerk.accounts.dev',
            'https://*.clerk.com',
            'https://clerk.homematch.pro',
            'https://accounts.homematch.pro',
            'https://challenges.cloudflare.com',
            'https://maps.googleapis.com',
            'https://pagead2.googlesyndication.com',
            'https://googleads.g.doubleclick.net',
            'https://tpc.googlesyndication.com',
            'https://securepubads.g.doubleclick.net',
            'https://fundingchoicesmessages.google.com',
            'https://ep1.adtrafficquality.google',
          ],
          'frame-src': [
            'https://*.clerk.accounts.dev',
            'https://*.clerk.com',
            'https://clerk.homematch.pro',
            'https://accounts.homematch.pro',
            'https://challenges.cloudflare.com',
            'https://pagead2.googlesyndication.com',
            'https://googleads.g.doubleclick.net',
            'https://tpc.googlesyndication.com',
            'https://securepubads.g.doubleclick.net',
            'https://fundingchoicesmessages.google.com',
          ],
          'worker-src': ["'self'", 'blob:'],
          'frame-ancestors': ["'none'"],
        },
      }
    : undefined

// Clerk route matcher for protected pages.
// M5 (2026-05-13 audit): derived from the single PROTECTED_PATH_PREFIXES
// source so a new route is added in one place. The trailing `(.*)` makes
// it path-prefix matching to mirror `isProtectedPath`'s `startsWith` form.
const isClerkProtectedRoute = createRouteMatcher(
  PROTECTED_PATH_PREFIXES.map((prefix) => `${prefix}(.*)`)
)

const getSafeRedirectPath = (value: string | null) => {
  if (!value) return null

  let decoded = value
  try {
    decoded = decodeURIComponent(value)
  } catch {
    return null
  }

  if (!decoded.startsWith('/')) return null
  if (decoded.startsWith('//')) return null
  if (decoded.includes('://')) return null

  return decoded
}

const applySecurityHeaders = (
  response: NextResponse,
  request?: NextRequest
) => {
  Object.entries(SECURITY_HEADERS).forEach(([key, value]) =>
    response.headers.set(key, value)
  )

  // A6 (2026-05-13 audit): emit a request ID for log correlation. If the
  // edge (Vercel, Cloudflare) already attached one, preserve it; otherwise
  // mint a fresh UUID. Available to handlers via the request headers
  // (read with request.headers.get('x-request-id')) and surfaced to the
  // client on the response so issues can be reported back with the ID.
  const incomingId =
    request?.headers.get('x-request-id') ||
    request?.headers.get('x-vercel-id') ||
    null
  const requestId = incomingId ?? crypto.randomUUID()
  response.headers.set('x-request-id', requestId)
  if (request && !request.headers.get('x-request-id')) {
    request.headers.set('x-request-id', requestId)
  }

  // HSTS in production only. The Content-Security-Policy is generated by
  // clerkMiddleware's `contentSecurityPolicy` option (see CSP_OPTIONS).
  if (process.env.NODE_ENV === 'production') {
    response.headers.set(
      'Strict-Transport-Security',
      'max-age=31536000; includeSubDomains; preload'
    )
  }

  return response
}

const redirectToLogin = (request: NextRequest): NextResponse => {
  // Resolve against request.url (the actual incoming host) so cookies
  // stay scoped to the host the user is on (e.g. 127.0.0.1 vs localhost,
  // or www.* vs apex). Cloning request.nextUrl sometimes normalizes the
  // host and causes session loss across the redirect.
  const target = new URL('/login', request.url)
  target.searchParams.set(
    'redirectTo',
    `${request.nextUrl.pathname}${request.nextUrl.search}`
  )
  return NextResponse.redirect(target)
}

/**
 * Top-level middleware wrapped with Clerk.
 *
 * Phase 3 (Supabase-auth elimination, 2026-05-13): Clerk is the only
 * identity source — the legacy Supabase session-refresh branch is gone.
 *
 * Flow:
 * - Public-bypass paths skip Clerk session resolution entirely.
 * - Clerk session is resolved with a timeout fallback (failure → anon).
 * - Signed-in users on /login or /signup get redirected to /dashboard
 *   (or a sanitized ?redirectTo target).
 * - Anonymous users hitting protected pages redirect to /login.
 * - API routes always pass through with security headers; route handlers
 *   re-verify the Clerk session themselves.
 *
 * The Content-Security-Policy is generated by the `contentSecurityPolicy`
 * option passed to clerkMiddleware below (see CSP_OPTIONS).
 */
export default clerkMiddleware(
  async (clerkAuth, request) => {
    const nextRequest = request as NextRequest
    const pathname = nextRequest.nextUrl.pathname

    // Fast path for public-bypass routes: skip Clerk session resolution
    // entirely. /api/health benchmarked at 574ms TTFB through the full
    // middleware vs ~50ms expected for a no-DB health probe — Clerk session
    // resolution + token validation was eating most of that. Same applies
    // to /api/webhooks/clerk (Svix signature is its own auth) and the
    // performance-metrics ingest beacon.
    if (PUBLIC_BYPASS_PATHS.some((path) => pathname.startsWith(path))) {
      return applySecurityHeaders(
        NextResponse.next({ request: nextRequest }),
        nextRequest
      )
    }

    // M3 (2026-05-13 audit): wrap clerkAuth() in a timeout. Without it,
    // Clerk SDK slowness (token verification, JWKS fetch, network blip)
    // hangs every request through middleware. Default 5s; override via
    // env for tighter SLAs.
    const clerkTimeoutMs = parseInt(
      process.env.MIDDLEWARE_CLERK_TIMEOUT_MS || '5000',
      10
    )
    let clerkUserId: string | null = null
    try {
      const clerkResult = await Promise.race([
        clerkAuth(),
        new Promise<{ userId: null }>((_, reject) =>
          setTimeout(
            () => reject(new Error('Clerk auth timeout')),
            clerkTimeoutMs
          )
        ),
      ])
      clerkUserId = clerkResult.userId ?? null
    } catch (err) {
      console.warn(
        '[Middleware] Clerk auth failed/timed out — treating as unauthenticated:',
        err instanceof Error ? err.message : err
      )
      clerkUserId = null
    }

    if (clerkUserId) {
      // Signed-in: redirect away from /login + /signup, otherwise pass through.
      let response = NextResponse.next({ request: nextRequest })

      if (pathname === '/login' || pathname === '/signup') {
        const params = nextRequest.nextUrl.searchParams
        const redirectTo =
          getSafeRedirectPath(params.get('redirectTo')) ||
          getSafeRedirectPath(params.get('redirect'))
        const target = new URL(redirectTo ?? '/dashboard', request.url)
        response = NextResponse.redirect(target)
      }

      return applySecurityHeaders(response, nextRequest)
    }

    // Anonymous from here on.
    //
    // API routes always pass through — every API handler re-verifies the
    // Clerk session via requireUserFromRequest, and many public endpoints
    // (search, properties feed) are intentionally anon-readable.
    if (pathname.startsWith('/api/')) {
      return applySecurityHeaders(
        NextResponse.next({ request: nextRequest }),
        nextRequest
      )
    }

    // Anonymous + protected page → /login.
    if (isProtectedPath(pathname)) {
      return redirectToLogin(nextRequest)
    }

    return applySecurityHeaders(
      NextResponse.next({ request: nextRequest }),
      nextRequest
    )
  },
  { contentSecurityPolicy: CSP_OPTIONS }
)

export const config = {
  matcher: [
    /*
     * Match all request paths except for the ones starting with:
     * - _next/static (static files)
     * - _next/image (image optimization files)
     * - favicon.ico (favicon file)
     * Feel free to modify this pattern to include more paths.
     */
    '/((?!_next/static|_next/image|_next/data|favicon.ico|.*\\.(?:svg|png|jpg|jpeg|gif|webp|js|css|json|xml|txt|ico|map|woff|woff2|ttf|otf)$).*)',
  ],
}

// Export the route matcher so other layers can reuse it (sanity check that
// PROTECTED_PATH_PREFIXES and isClerkProtectedRoute stay in sync).
export { isClerkProtectedRoute }
